name: Playwright Pytest UI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
          pip install playwright
          playwright install

      - name: Run UI Tests
        run: |
         pytest tests/ --html=report.html --self-contained-html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: TestReports
          path: report.html
